### ISSUE TITLE
hybridauth popup doesn't close after login

### ISSUE THREAD

**Issue by srakl** [hybridauth/hybridauth#1230] opened 2020-09-15 14:41 UTC
I'm using hybridauth v3 for my Yii app,

in my view i have this code

    $popupScript = "function auth_popup( provider, title = 'Authentication Window', w = '500', h = '650' ){
    
        var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
        var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;
    
        width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
        height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;
    
        var left = ((width / 2) - (w / 2)) + dualScreenLeft;
        var top = ((height / 2) - (h / 2)) + dualScreenTop;
        var options = 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no';
    
        var url = '".Yii::app()->createAbsoluteUrl('/usr/hybridauth/callback')."?provider='+provider;
    
        var authWindow = window.open(url, title, options+', width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);
        
        if (window.focus) {
            authWindow.focus();
        }
    
        return false;
    }";
    
    Yii::app()->clientScript->registerScript(__CLASS__.'#popup', $popupScript, CClientScript::POS_END);

and in my controller i have this, i tried both the close() and still same result.

    // Close pop-up window
    				echo "<script>
    						//window.opener.location.replace('".$url."');
    						//window.close();
    						window.opener.location.href = '".$url."';
    						window.open('', 'authWindow').close();
    					</script>";

when i login using google, it log's in but the popup windows doesn't close. and it redirects in the popup. Anyone have a solution for this? Thanks

**Comment by chrisgraham** [comment] 2020-09-21 04:38
This is probably a duplicate of #1100. Are there any errors in the browser's JS Console?

**Comment by srakl** [comment] 2020-09-21 05:05
I did try those solutions before i posted this questions. And my website is using https. Nope, no errors. Should i share the Yii php wrapper class?

**Comment by chrisgraham** [comment] 2020-09-21 17:22
I'll try and debug for you if you can somehow provide a fully working standalone test project.

**Comment by ApacheEx** [comment] 2020-09-21 19:01
can you try this if it works for you?

```js
var authWindow = window.open(url, title, options+', width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);
window.closeAuthWindow = function () {
  authWindow.close();
}

```
and then when you want to close you simply add this:
```js
if (window.opener.closeAuthWindow) {
  window.opener.closeAuthWindow();
}
```

**Closed** 2020-09-21 19:26 UTC
Labels: contributions: welcome :1st_place_medal:, issue: bug :bug:, tag: documentation :memo:, tag: v3
