### ISSUE TITLE
last version broken

### ISSUE THREAD

**Issue by nightw0lv** [hybridauth/hybridauth#713] opened 2016-12-27 09:34 UTC
Hybrid_Auth::getConnectedProviders() is not returning what it should like 2.7.0 i use
facebook login has error (tested on 2.8.2 - 2.8.3-dev)
at this point i cant test more i have to return in buggy 2.7.0 with the custom fixes found here

[27-Dec-2016 09:13:36 UTC] PHP Fatal error:  Uncaught Error: Class 'Facebook\Facebook' not found in Hybrid/Providers/Facebook.php:56
Stack trace:
#0 Hybrid/Provider_Model.php(99): Hybrid_Providers_Facebook->initialize()
#1 Hybrid/Provider_Adapter.php(101): Hybrid_Provider_Model->__construct('Facebook', Array, Array)
#2 Hybrid/Auth.php(277): Hybrid_Provider_Adapter->factory('Facebook', Array)
#3 Hybrid/Endpoint.php(129): Hybrid_Auth::setup('Facebook')
#4 Hybrid/Endpoint.php(51): Hybrid_Endpoint->processAuthStart()
#5 Hybrid/Endpoint.php(72): Hybrid_Endpoint->__construct(Array)
#6 /index.php(15): Hybrid_Endpoint::process()
#7 {main}
  thrown in /Hybrid/Providers/Facebook.php on line 56

**Comment by jmgomezpoveda** [comment] 2017-01-04 00:04
This is a duplicate of https://github.com/hybridauth/hybridauth/issues/698

**Closed** 2017-04-30 06:30 UTC
