### ISSUE TITLE
Packagist.org have not registry the last version (v2.13.0)

### ISSUE THREAD

**Issue by ajcerezo** [hybridauth/hybridauth#1034] opened 2019-01-15 08:23 UTC
## Bug

I can not install v2.13.0 because this version not registry in packagist.org as stable version.

### Version and provider

v2.13.0

### Reproduction

xxxxx@yyyy:~ $ composer require hybridauth/hybridauth:^2.13
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package hybridauth/hybridauth ^2.13 is satisfiable by hybridauth/hybridauth[v2.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

Very Thanks

**Comment by ApacheEx** [comment] 2019-01-16 09:49
closed as duplicate of #1032

**Closed by ApacheEx** 2019-01-16 09:49 UTC
