### ISSUE TITLE
The authorization state [state=***] of this page is either invalid or has already been consumed

### ISSUE THREAD

**Issue by otengkwame** [hybridauth/hybridauth#1301] opened 2021-06-25 09:09 UTC
## Bug, feature or question?
Hi, Team

I am trying to implement an authentication with LinkedIn and I keep getting this error.

**The authorization state [state=HA-*] of this page is either invalid or has already been consumed**

I have looked through the documentation to try and fix this because I thought it has already been consumed so I can logout and reconnect again.

As at now I haven't found a solution to go around this. 

### Version and provider
The provider is LinkedIn and the version is 3.7

**Comment by confettidc** [comment] 2021-12-28 09:36
Hi, Team,

I got same error too:

[Hybridauth\Exception\InvalidAuthorizationStateException] The authorization state [state=xxxxxxxx] of this page is either invalid or has already been consumed.

I used the hybridauth 3.0 few months ago for my project.

However, I got this error when use hybridauth to login my system today.

Any suggestion and idea to solve the issue?

Thanks.

**Comment by KaylaLamp** [comment] 2022-01-04 14:39
Has anyone found a solution for this?

It randomly started happening on my sites as well, when I've made no changes. I even tried to test the demos and the same error comes through.

**Comment by jamminjames** [comment] 2022-06-11 10:06
Yes, it seems random for me too. Get it all working, then BAM. It seems to having something to do with the session storage. Whenever this happens, at the same time, Hybridauth seems to be wiping out its session storage after authentication.  Can't figure out why, don't think I've changed anything that would affect it. I really wish someone who knows would help out on this forum. Seems almost abandoned.

**Comment by jamminjames** [comment] 2022-06-12 05:53
Okay, I figured out the problem in my case, maybe it will help with yours. 

Please see my issue post #1334.

**Comment by kousu** [comment] 2023-02-28 04:41
I'm seeing the same symptoms with Discord: logging in is fine for most people most of the time, but some browsers seem to get jammed and making logging in impossible.

This is the same bug: https://github.com/zorn-v/nextcloud-social-login/issues/386

**Comment by ApacheEx** [comment] 2023-08-27 16:28
The related PR was already merged and will be released as part of 3.11 soon

**Closed by ApacheEx** 2023-08-27 16:28 UTC

**Comment by mirko46** [comment] 2023-11-14 15:56
Hi, I tried solution suggest from @kousu but I have always same error.
I've apparenty solved with this workaround:
```php
--- a/src/Adapter/OAuth2.php
+++ b/Adapter/OAuth2.php
@@ -423,6 +423,7 @@ abstract class OAuth2 extends AbstractAdapter implements AdapterInterface
         if ($this->supportRequestState
             && $this->getStoredData('authorization_state') != $state
         ) {
             $this->deleteStoredData('authorization_state');
+            $this->authenticateBegin();
             throw new InvalidAuthorizationStateException(
                 'The authorization state [state=' . substr(htmlentities($state), 0, 100) . '] '
                 . 'of this page is either invalid or has already been consumed.'
``` 
So instead to throw error restart begin function to generate new authorization state.
What about that?

**Comment by owenkavanagh** [comment] 2024-08-08 09:20
If you are using an application load balancer with multiple instances, please check that session stickiness is enabled! This was the cause of our issue, took us a while to figure it out, so I'm hoping this comment will help someone still having the same issue.
