### ISSUE TITLE
The authorization state ** of this page is either invalid or has already been consumed

### ISSUE THREAD

**Issue by sNniffer** [hybridauth/hybridauth#893] opened 2017-12-14 21:11 UTC
I always use the hybridauth library for social login via php, but when deploying to a new system, it always returns me this error:

`    Oops, we ran into an issue! The authorization state [state=HA-87J6MLDU2T0F514HVCBSPWGXIZOEY3NRKQA9] of this page is either invalid or has already been consumed.
`

I already tested in different browsers and with social networks Google and Facebook, the script redirects to the social network and after logging in the error returned in the uri url is this up

I use the PHP Version 5.6.32

**Comment by ApacheEx** [comment] 2017-12-17 21:37
1) which version of HA do you use?
2) is this error returned for all social providers?

**Comment by sNniffer** [comment] 2018-01-04 18:54
Hi

- HA version is Hybridauth 3
- Tested with Facebook, G+ and Linkedin

**Comment by ApacheEx** [comment] 2018-01-06 10:07
can you show how you do login? would be nice to see any code examples.

**Comment by sNniffer** [comment] 2018-01-06 16:50
My code is:
`<?php
session_start();
	include 'social_register.php';

	// include hybridauth lib
	$base_url_callback = 'http://site.com.br/controller/social_login.php?login='.$_GET["login"];
	
	$config_facebook = [
		'callback' => $base_url_callback,
		'keys' => [ 'key' => '*************', 'secret' => '**************' ]
	];

		$config_google = [
			'callback' => $base_url_callback,
			'keys' => [ 'key' => '************-f38fd0v5rltkb65cu8lua1fdfgfgatvk.apps.googleusercontent.com', 'secret' => 'u-1zNhsYX-**************' ]
		];

		$config_linkedin = [
			'callback' => $base_url_callback,
			'keys' => [ 'key' => '**************', 'secret' => '**************' ]
		];
 
		
	require_once( "biblio/hybrid/autoload.php" );

	if( isset( $_GET["login"] ) )
	{
		if( $_GET["login"] =='facebook') 
		{
			$adapter = new Hybridauth\Provider\Facebook($config_facebook);

		}
		elseif( $_GET["login"] =='google') 
		{
			$adapter = new Hybridauth\Provider\Google($config_google);
		}
		elseif( $_GET["login"] =='linkedin') 
		{
			$adapter = new Hybridauth\Provider\LinkedIn($config_linkedin);
		}
			try {
 				$adapter->authenticate();
				$isConnected = $adapter->isConnected();
				$userProfile = $adapter->getUserProfile();
				//var_dump($userProfile);

				$adapter->disconnect();
			}
				catch(\Exception $e){
					echo 'Oops, we ran into an issue! ' . $e->getMessage();
				}
	}

	if( ! isset( $userProfile ) )
	{
		if(isset($_SESSION['RedirecionaLogin']))
		{
			$redireciona = base64_decode($_SESSION['RedirecionaLogin']);
		}
		else
		{
			$redireciona = 'http://site.com.br/painel/meus-anuncios';
		}
	}
	
	else{
		$user = new User();
		$user_data = $user->checkUser($_GET["login"],$userProfile->identifier,$userProfile->displayName,$userProfile->email,$userProfile->photoURL);
 
		if(isset($_SESSION['RedirecionaLogin']))
		{
			$redireciona = base64_decode($_SESSION['RedirecionaLogin']);
		}
		else
		{
			$redireciona = 'http://site.com.br/painel/meus-anuncios';
		}
	}
`

**Comment by sNniffer** [comment] 2018-01-06 16:53
is there any configuration in the hosting for hybridauth to work?

-PHP 5.4+
-PHP Session
-PHP cURL

they are OK

**Comment by ApacheEx** [comment] 2018-01-06 20:58
Here is example how to organize multiple providers login. Perhaps it would be helpful.

https://github.com/hybridauth/hybridauth/tree/master/examples/example_06

**Comment by ApacheEx** [comment] 2018-01-06 21:02
just to be sure, am I right you have:

- `http://site.com.br/controller/social_login.php?login=facebook` as `Valid OAuth redirect URIs` for Facebook.
- `http://site.com.br/controller/social_login.php?login=linkedin` as `Authorized Redirect URLs` for LinkedIn.
- etc..

**Comment by sNniffer** [comment] 2018-01-08 11:53
Hi ApacheEx,

urls are in the network settings uri.

I tested configuring a different url and the social networks returned saying that the urls are not in the valid uris configured, I believe it is some kind of hybridauth bug, I'll remove it and add it again

**Comment by sNniffer** [comment] 2018-01-08 14:20
I switched to version 2, and the same error occurs

**Comment by sagudev** [comment] 2018-01-15 14:28
Then something is wrong on your side. Did you just change version or did you changes scripts that uses hybridauth too? If you have hosting proider install server on your pc [(like this one)](https://winnmp.wtriple.com/) and install hybridauth and test it.

**Comment by ApacheEx** [comment] 2018-01-18 22:27
@sNniffer,
I can't reproduce this issue, would you mind to create a test repository with your code or so? Is it still actual?

**Comment by sagudev** [comment] 2018-01-19 06:01
Probably not

**Comment by cubecoffee** [comment] 2018-01-30 14:37
It's still a relevant problem.

It comes from **Hybridauth\Adapter\OAuth2** which comes up with:

> An opaque value used by the client to maintain state between the request and callback. The authorization server includes this value when redirecting the user-agent back to the client.

I guess it happens if you add your own get parameters to the callback url. What do we have to change?

**Comment by ApacheEx** [comment] 2018-02-10 08:51
I still think it's a server/hosting related issue and Hybrydauth can't do anything here. I'm going to close the issue. Otherwise, you need to provide a full example of your code where it reproducible.

**Closed by ApacheEx** 2018-02-10 08:51 UTC
Labels: Possible bug

**Comment by kowach** [comment] 2018-08-24 12:45
I had same error. It was problem with custom Phalcon session database adapter. So I implemented `\Hybridauth\Storage\StorageInterface` and put it in `\Hybridauth\Hybridauth($config, null, new MyPhalconHybridStorage());` constructor.

**Comment by elcreator** [comment] 2019-11-25 02:27
Looks like it should be enough but it not works
```php
use Hybridauth\Storage\StorageInterface;

class HybridAuthSessionStorage implements StorageInterface
{
    /** @var \Phalcon\Session\Manager  */
    private $_session;
    private $_keys = [];

    public function __construct(\Phalcon\Session\Manager $session)
    {
        $this->_session = $session;
    }

    public function get($key)
    {
        return $this->_session->get($key);
    }

    public function set($key, $value)
    {
        $this->_session->set($key, $value);
        if (!in_array($key, $this->_keys)) {
            $this->_keys[] = $key;
        }
    }

    public function delete($key)
    {
        $this->_session->remove($key);
    }

    public function deleteMatch($key)
    {
        $this->_session->remove($key);
    }

    public function clear()
    {
        foreach ($this->_keys as $key) {
            if ($this->_session->has($key)) {
                $this->_session->remove($key);
            }
        }
    }

}
```

**Comment by mhdhamouday** [comment] 2020-04-29 08:05
I had same error.

**Comment by sagudev** [comment] 2020-04-29 08:07
> I have same error.

Can you share your code?

**Comment by dheerajmohantopgear** [comment] 2020-05-02 18:28
HI, I have the same error for my Dokan marketplace. I am using the inbuilt plugin settings. Can someone help me resolve the issue? Is the issue on the hosting side? 
When a new user login, the login happens normally. Once they logout and tries to login, the same error "The authorization state of this page is either invalid or has already been consumed social login error" comes up. 

Please help resolve this asap

**Comment by ApacheEx** [comment] 2020-05-03 07:16
@dheerajmohantopgear, is it possible to provide some code example, how you integrate and use this library?

**Comment by achatainga** [comment] 2020-06-06 00:21
I had this issue and in my case this was the problem:
1) I setup 3 providers Facebook, Twitter and Google. Facebook and Twitter allow local ip addresses like **_192.168.0.100_** so I used that as redirect callback to my php scripts (_Something like https://192.168.0.100/socialnetwork_login.php_). Google however requires a Top Level Domain (**_TLD_**) so I edited my hosts file on "C:/windows/system32/drivers/etc" to point to a fake (but valid) TLD: (within hosts)
`192.168.0.100 example.com`

Then I edited my Apps to point the allowed callback to be something like https://example.com/socialnetwork_login.php

2) I forgot to edit the proper links so I had an issue when login in and login out since sometimes I had **_192.168.0.100_** and other times **_example.com_**.

To fix it, I basically kept developing using my TLD **_example.com_** and made sure to edit each provider App accordingly. Next, I made sure to include this lines right before proceeding with the login part:
`$hybridauth = new Hybridauth\Hybridauth( $config );`
`$hybridauth->disconnectAllAdapters(); //<< this line`

Next lines for reference:
`$adapter = $hybridauth->authenticate( "Facebook" );`
`$isConnected = $adapter->isConnected();`
`$userProfile = $adapter->getUserProfile();`

**Comment by topproto** [comment] 2020-07-14 06:08
I caused this simply by putting app.cookieDomain = '.app.localhost' inside my .env config.

**Comment by developnow** [comment] 2022-11-17 18:35
In my case, this happened because of letting pass a lapse of time between receiving the token and using it.

**Comment by owenkavanagh** [comment] 2024-08-08 09:21
If you are using an application load balancer with multiple instances, please check that session stickiness is enabled! This was the cause of our issue, took us a while to figure it out, so I'm hoping this comment will help someone still having the same issue.
