### ISSUE TITLE
Support LinkedIn Migration from v1 to v2

### ISSUE THREAD

**Issue by zhenbo** [hybridauth/hybridauth#1046] opened 2019-02-07 20:33 UTC
## Bug, feature or question?
This is a feature 
This feature related to LinkedIn. LinkedIn recently forced migration from v1 to v2 API. All v1 APIs are shutdown at Mar 1st 2019.  Is hybridauth going to support LinkedIn v2. Here is more information about this migration. https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context
### Version and provider
What version of Hybrid Auth does this relates to?
2.13
Is this an issue with a provider? If yes, which one?
Yes, it is a provider, it is LinkedIn

**Comment by ApacheEx** [comment] 2019-02-08 07:53
yeah, we already discussed it here: https://github.com/hybridauth/hybridauth/issues/1020

**Comment by ApacheEx** [comment] 2019-02-16 13:22
closed as duplicate of #1020

**Closed by ApacheEx** 2019-02-16 13:22 UTC
