### ISSUE TITLE
LinkedIn not working anymore

### ISSUE THREAD

**Issue by christ0ph3r** [hybridauth/hybridauth#470] opened 2015-05-15 20:45 UTC
LinkedIn doesn't seem to be working anymore.  Looks like they did a major update.

**Comment by cybermania** [comment] 2015-05-15 23:20
They did. Announced on devs: developer.linkedin.com 
Not sure are the new APIs/changes included in the new releases.

**Comment by christ0ph3r** [comment] 2015-05-15 23:23
I would like to know.  It looks like our app is using a little bit older version of hybrid auth.  Do you know any ways to test locally with LinkedIn API ? @cybermania

**Comment by satya5561** [comment] 2015-05-16 02:09
i am facing same problem. please update your api.

**Comment by wvdweij** [comment] 2015-05-19 11:12
LinkedIn has updated their API between the 12th and 19th of may. Generally there are some rights changed thus updating your application scope should do the trick. If you're not requesting any scope params in your Hybridauth config you need to change the rights in the LinkedIn Developer Application Settings. For more information see: https://developer.linkedin.com/support/developer-program-transition especially check the Troubleshooting section on this page for further details of the api changes.

**Comment by brecht27** [comment] 2015-05-20 08:50
Can anyone tell me how to change the API settings in the hybridauth to make it work again? I have read the documentation descibed by wvdweij but still no result.
It is very urgent.

**Comment by wvdweij** [comment] 2015-05-20 09:14
If you're requesting any of the following permissions: r_fullprofile, r_network, r_contactinfo, rw_nus, rw_groups, w_messages. You need to remove them from the scope parameter in the Hybridauth settings or uncheck the permissions in the LinkedIn Application Configuration.

**Comment by brecht27** [comment] 2015-05-20 10:41
Where can i find the scope parameter in the Hybridauth settings?
The only thing i have checked is the basicprofile in the linkedin app config.

**Comment by wvdweij** [comment] 2015-05-20 10:44
If the scope parameter isn't present than unchecking the permissions in the LinkedIn Application Configuration should be sufficient. If the error still occurs the you should tun on the debug_info and debug_file params in the Hybridauth config so you can analyse the logs and figure out whats causing the LinkedIn errors.

**Comment by brecht27** [comment] 2015-05-20 10:55
I have set the debug option to true in the config file of hybridauth and i have the 'Oops. Error. ' Message. That is all i have... I have also checked the w_share permission in the linkedin app config.
Nothing has changed.

**Comment by wvdweij** [comment] 2015-05-20 11:07
Check the entries in the debug log of Hybridauth and post them here. Maybe there's some more information regarding the error.

**Comment by brecht27** [comment] 2015-05-20 14:12
I have setup a debug log file in the hybridauth config file. But if looked into the hybridauth.log file it's empty...		

"debug_mode" => true,
"debug_file" => "/temp/hybridauth.log"

**Comment by vasumeda** [comment] 2015-05-20 15:43
I am facing the same issue. 

Here's the message from the log file. Any help is really appreciated

DEBUG -- ::1 -- 2015-05-20T11:39:55-04:00 -- Hybrid_Auth initialize. dump used config:  -- a:8:{s:8:"base_url";s:43:"http://localhost/spark/index.php/site/oauth";s:9:"providers";a:10:{s:6:"OpenID";a:1:{s:7:"enabled";b:0;}s:3:"AOL";a:1:{s:7:"enabled";b:0;}s:5:"Yahoo";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}s:6:"Google";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}s:8:"Facebook";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}s:7:"Twitter";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:4:"Live";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}s:7:"MySpace";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:8:"LinkedIn";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:14:"dsdsdsdsdssss";s:6:"secret";s:16:"sdsdsdsdsd";}}s:10:"Foursquare";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}}s:10:"debug_mode";b:1;s:10:"debug_file";s:43:"/Applications/XAMPP/logs/srini_linkedin.log";s:9:"path_base";s:90:"/Applications/XAMPP/xamppfiles/htdocs/spark/protected/extensions/hoauth/hybridauth/Hybrid/";s:14:"path_libraries";s:101:"/Applications/XAMPP/xamppfiles/htdocs/spark/protected/extensions/hoauth/hybridauth/Hybrid/thirdparty/";s:14:"path_resources";s:100:"/Applications/XAMPP/xamppfiles/htdocs/spark/protected/extensions/hoauth/hybridauth/Hybrid/resources/";s:14:"path_providers";s:100:"/Applications/XAMPP/xamppfiles/htdocs/spark/protected/extensions/hoauth/hybridauth/Hybrid/Providers/";}
DEBUG -- ::1 -- 2015-05-20T11:39:55-04:00 -- Hybrid_Auth initialize. dump current session:  -- a:5:{s:26:"hauth_session.error.status";s:4:"i:1;";s:27:"hauth_session.error.message";s:78:"s:70:"Authentication failed! LinkedIn returned an invalid Token. Response:  ";";s:24:"hauth_session.error.code";s:4:"i:5;";s:25:"hauth_session.error.trace";s:1516:"s:1506:"#0 /Applications/XAMPP/xamppfiles/htdocs/spark/protected/extensions/hoauth/hybridauth/Hybrid/Endpoint.php(140): Hybrid_Providers_LinkedIn->loginBegin()

**Comment by vasumeda** [comment] 2015-05-26 11:24
Hello All,

Any luck with the issue. Anybody has any workaround?

Thanks
-Srini

**Comment by johnshepherd** [comment] 2015-06-04 09:40
Try setting the `Default "Cancel" Redirect URL:` in the App settings on the Linked Developer portal

**Comment by cybermania** [comment] 2015-06-04 15:46
@christ0ph3r I've been using also an older version of the hybridauth. Updated the linkedin libraries and it worked OK after that.

**Comment by brecht27** [comment] 2015-06-05 18:29
No, they don't updated the linkedin library for the more complex app like i use. If you change the linkedin libraries to the newest version of hybridauth you have the same issue like before :-(

**Comment by VladyslavKurmaz** [comment] 2015-06-10 07:10
Hi Team.
I have faced with the same issue.
In my case solution was to fill all required fields at the app settings area.
I didn't enter valid https url to the app's logo "Application Logo URL:Required*"

Please check all fields, then authentication should work.
P.S. I'm using hybridauth-2.4.2-dev

**Comment by cirdev** [comment] 2015-06-12 14:49
With an image in https and all mandatories fields written, the problem is the same.
Anyone has a solution ?

**Comment by VladyslavKurmaz** [comment] 2015-06-12 15:54
I made screenshots from my app settings.
Please check it and compare with yours.
http://i.imgur.com/OYxK7oE.png

What I can suggest more, is that your site have be only https based now.
I marked corresponding edit boxes with red lines.

Hope, this will help.

**Comment by christ0ph3r** [comment] 2015-06-16 21:57
Thank you! @wvdweij and @VladyslavKurmaz  

You guys tips helped me.  I had 1 old permission checked causing it not to work and realized I had to add a cancel URL.

One issue I have is before I was able to get the number of connections a linked in user has.  Now that is not working for me.  How do I get this to work with new API update?  Any suggestions?

**Comment by VladyslavKurmaz** [comment] 2015-06-17 07:11
@christ0ph3r 
As far, as I understood, LinkedIn made the same step as a Facebook - fully close public access to the connections/contacts API
According to this: https://developer.linkedin.com/support/developer-program-transition
> If your application is currently using any other API services (e.g. Connections, Groups, People
> Search, Invitation, Job Search, etc.) you will have to apply to become a member of a relevant Partner 
> Program that provides the necessary API access to continue to leverage any of the endpoints that
> are not listed above.

__so, we need to join some *Partner Program * to continue be able use this feature.__

@AdwinTrave looks like we can close this issue.

**Comment by christ0ph3r** [comment] 2015-06-17 07:36
Is there any way to get it with num-connections since it supports r_basicprofile? 

https://developer.linkedin.com/docs/fields/basic-profile

**Comment by cirdev** [comment] 2015-06-17 07:53
@VladyslavKurmaz 
Thank you, i applied https everywhere, i have always 
> Authentication failed! LinkedIn returned an invalid Token
It's not clear for me the problem is in the Hybrydauth API or in the linkedIn parameters and permissions ?

**Comment by VladyslavKurmaz** [comment] 2015-06-17 08:29
@cirdev 
Looks like Hybrydauth API is ok and we need to check app settings & hybridauth config.

What I would suggest as check-list:
* update to the latest stable hybridauth version (i'm using hybridauth-2.4.2-dev branch)
* fill all edit-boxes at the linkedin app settings (see my screenshot above), https link to app logo have to be accessible no only filled.
* here is part of my config

>                "LinkedIn" => array ( 
>                    "enabled" => true,
>                    "keys"    => ...,
>                ),
as you can see, there are no special configurations
* register one more test linkedin app and test your app using this temp one.
* delete all local session files saved by hybridauth

**Comment by VladyslavKurmaz** [comment] 2015-06-17 19:14
@christ0ph3r 
I found only two fields at r_basicprofile, which are related to the information about contacts: num-connections and num-connections-capped.
I tested it on my linkedin profile and received capped number of my connections.
> `<num-connections>500</num-connections>`
> `<num-connections-capped>true</num-connections-capped>`

And this is only info about connections we can get with r_basicprofile authorization permission.

**Comment by drupalninja** [comment] 2015-06-24 21:29
I am getting "OAuth callback URL was not confirmed by the LinkedIn end-point"

**Comment by drupalninja** [comment] 2015-06-24 21:34
Also get "Scope NOT_AUTHORIZED : rw_groups, Scope NOT_AUTHORIZED : rw_nus, Scope NOT_AUTHORIZED : r_network, Scope NOT_AUTHORIZED : r_contactinfo, Scope NOT_AUTHORIZED : r_fullprofile"

This used to work before LinkedIn updated their API. I have all the perms checked.

**Comment by christ0ph3r** [comment] 2015-06-24 21:37
@drupalninja 

It sounds like you still have old permissions checked.   Uncheck all the permissions and save.   A few will go away because they are old.  Then recheck the ones you need and resave.

**Comment by drupalninja** [comment] 2015-06-24 21:40
So I got it to work when I changed this line temporarily as a way to debug:
const _URL_REQUEST                 = 'https://api.linkedin.com/uas/oauth/requestToken?scope=r_basicprofile+r_emailaddress';

**Comment by drupalninja** [comment] 2015-06-24 21:41
@christ0ph3r I will try what you suggested

**Comment by drupalninja** [comment] 2015-06-24 21:43
@christ0ph3r you were right, I had to reset perms. I don't know which perm I need to fetch info ab a company (public info I think?).

**Closed** 2015-07-20 00:19 UTC
Labels: Bug, Provider
